version: '3'

services:
  mixtura-app:
    build:
      context: .
      dockerfile: docker/Dockerfile.nodejs
    command: nodemon --legacy-watch src/server.ts
    image: mixtura-app
    container_name: mixtura-app
    restart: unless-stopped
    env_file: .env
    ports:
      - "80:80"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
    networks:
      - app-network
  mixtura-data:
    image: 'mongo:4.0.23'
    container_name: mixtura-data
    restart: always
    env_file: db.env
    ports:
      - '27017:27017'
    volumes:
      - ./mongo-volume:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - app-network
networks:
  app-network:
    driver: bridge

volumes:
  mongo-volume:
  node_modules: